'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EveHQ.Void.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Plugin_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Plugin_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 30463,1381,9
        '''30463,1382,3600
        '''30463,1383,1000000000
        '''30463,1384,50000000
        '''30463,1385,150000000
        '''30463,1457,0
        '''30579,1381,1
        '''30579,1382,960
        '''30579,1383,100000000
        '''30579,1384,0
        '''30579,1385,20000000
        '''30579,1457,296
        '''30583,1381,2
        '''30583,1382,960
        '''30583,1383,750000000
        '''30583,1384,0
        '''30583,1385,300000000
        '''30583,1457,297
        '''30584,1381,3
        '''30584,1382,1440
        '''30584,1383,1000000000
        '''30584,1384,0
        '''30584,1385,300000000
        '''30584,1457,298
        '''30642,1381,4
        '''30642,1382,1440
        '''30642,1383,1000000000
        '''30642,1384,0
        '''30642,1385,300000000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WHattribs() As String
            Get
                Return ResourceManager.GetString("WHattribs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000001,1
        '''11000002,1
        '''11000003,1
        '''11000004,2
        '''11000005,2
        '''11000006,2
        '''11000007,2
        '''11000008,2
        '''11000009,3
        '''11000010,3
        '''11000011,3
        '''11000012,3
        '''11000013,3
        '''11000014,3
        '''11000015,3
        '''11000016,4
        '''11000017,4
        '''11000018,4
        '''11000019,4
        '''11000020,4
        '''11000021,4
        '''11000022,4
        '''11000023,4
        '''11000024,5
        '''11000025,5
        '''11000026,5
        '''11000027,5
        '''11000028,5
        '''11000029,5
        '''11000030,6
        '''.
        '''</summary>
        Friend ReadOnly Property WHClasses() As String
            Get
                Return ResourceManager.GetString("WHClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 146,2,920,263,3,6,0,0,0,15,Shield HP Bonus
        '''169,2,920,70,3,6,0,0,5,15,Inertia Modifer
        '''237,2,920,76,3,6,0,0,0,15,Targeting Range Bonus
        '''243,2,920,76,3,6,0,0,5,15,Max Range Multiplier
        '''244,2,920,160,2,53;55;74,0,0,5,15,Tracking Speed Multiplier
        '''517,2,920,158,2,53;55;74,0,0,5,15,Falloff Modifer
        '''652,2,920,552,3,6,0,0,0,15,Signature Penalty
        '''1465,2,920,267,3,6,0,0,2,15,Armor EM Resistance Bonus
        '''1466,2,920,269,3,6,0,0,2,15,Armor Kin Resistance Bonus
        '''1467,2,920,270,3,6,0,0,2,15,Armor Therm Resistance Bonus
        '''1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WHEffects() As String
            Get
                Return ResourceManager.GetString("WHEffects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to J100009,Pulsar
        '''J100040,Black Hole
        '''J100046,Cataclysmic Variable
        '''J100118,Magnetar
        '''J100150,Black Hole
        '''J100237,Wolf Rayet
        '''J100328,Black Hole
        '''J100422,Red Giant
        '''J100447,Black Hole
        '''J100616,Pulsar
        '''J100651,Red Giant
        '''J100702,Black Hole
        '''J100724,Red Giant
        '''J100728,Red Giant
        '''J100744,Cataclysmic Variable
        '''J100846,Black Hole
        '''J100919,Wolf Rayet
        '''J100937,Cataclysmic Variable
        '''J101000,Cataclysmic Variable
        '''J101012,Red Giant
        '''J101042,Cataclysmic Variable
        '''J101145,Pulsar
        '''J101336,Cataclysmic Variable
        '''J101343,Wol [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WSpaceTypes() As String
            Get
                Return ResourceManager.GetString("WSpaceTypes", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
