'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EveHQ.HQF.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10001,Radius,Radius,0,m,1
        '''10002,Mass,Mass,0,kg,1
        '''10003,Volume,Volume,0,m3,1
        '''10004,Capacity,Capacity,0,m3,1
        '''10005,Drone Control,Drone Control,0,,0
        '''10006,Fighter Control,Fighter Control,0,,0
        '''10007,Drone Control Range,Drone Control Range,0,,0
        '''10008,Fighter Control Range,Fighter Control Range,0,,0
        '''10009,Warp Core Strength,Warp Core Strength,0,,6
        '''10010,Thrust Addition,Thrust Addition,0,,6
        '''10011,energyTurretROF,Rate Of Fire,0,s,9
        '''10012,hybridTurretROF,Rate Of Fire,0,s,9
        '''10013,projectileTurretROF,Rate  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Attributes() As String
            Get
                Return ResourceManager.GetString("Attributes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property BC() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("BC", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #HQF Booster Mapping Table,,,,,
        '''#Booster ID,IsPen,Effect ID,Group,Booster,Effect
        '''10155,0,548,Improved,Blue Pill,Shield Boost Bonus
        '''10151,0,848,Improved,Crash,Explosion Velocity Bonus
        '''15477,0,244,Improved,Drop,Tracking Speed Bonus
        '''15480,0,895,Improved,Exile,Armor Repair Bonus
        '''15461,0,294,Improved,Frentix,Turret Optimal Range Bonus
        '''15464,0,1079,Improved,Mindflood,Capacitor Bonus
        '''10165,0,349,Improved,Soothsayer,Turret Falloff Bonus
        '''15458,0,554,Improved,Xinstict,Sig Radius Bonus
        '''9950,0,548,Standard,Bl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BoosterEffects() As String
            Get
                Return ResourceManager.GetString("BoosterEffects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clipboard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clipboard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Omni-Damage&gt;,2500,2500,2500,2500
        '''Amarr Empire,4810,73,1837,3280
        '''Angel Cartel,1088,5871,1893,1148
        '''Blood Raiders,4524,10,1215,4251
        '''Caldari State,166,0,7264,2570
        '''CONCORD,3936,2280,2831,953
        '''Gallente Federation,230,0,4383,5387
        '''Guristas,0,0,8363,1637
        '''Khanid,5216,83,753,3948
        '''Minmatar Republic,2127,5151,1905,817
        '''Mordu&apos;s Legion,267,0,8123,1610
        '''Pure EM,10000,0,0,0
        '''Pure Explosive,0,10000,0,0
        '''Pure Kinetic,0,0,10000,0
        '''Pure Thermal,0,0,0,10000
        '''Rogue Drone,761,5515,1934,1790
        '''Sanshas Nation,5983,0,798,3219 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DamageProfiles() As String
            Get
                Return ResourceManager.GetString("DamageProfiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;No Resists&gt;,0,0,0,0,0,0,0,0,0,0,0,0
        '''Omni-Resists,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500
        '''Omni-Resists (No Hull),2500,2500,2500,2500,2500,2500,2500,2500,0,0,0,0
        '''.
        '''</summary>
        Friend ReadOnly Property DefenceProfiles() As String
            Get
                Return ResourceManager.GetString("DefenceProfiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #HQF Attribute Mapping Table,,,,,,,,,,
        '''#Affecting Attribute,Affecting Type,Affecting ID,Affected Attribute,Affected Type,Affected ID,Stack Nerf,Per Level,Calc Type,State,Description
        '''# SKILL ATTRIBUTE MAPPING,,,,,,,,,,
        '''# DRONES,,,,,,,,,,
        '''459,1,23566,10007,3,6,0,1,1,0,Advanced Drone Avionics
        '''280,1,24613,763,2,407,0,1,10,0,Advanced Drone Interfacing
        '''292,1,12484,64,5,12484,0,1,0,0,Amarr Drone Specialization
        '''292,1,12487,64,5,12487,0,1,0,0,Caldari Drone Specialization
        '''459,1,3437,10007,3,6,0,1,1,0,Drone Av [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Effects() As String
            Get
                Return ResourceManager.GetString("Effects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Eve() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Eve", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EveSpaceAttacker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EveSpaceAttacker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EveSpaceTarget() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EveSpaceTarget", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgArmor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgArmor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCalibration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCalibration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCapAverage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCapAverage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCapBal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCapBal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCapPeak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCapPeak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCargo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCargo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCPU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCPU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgDoomsday() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgDoomsday", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgDrone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgDrone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgDroneBay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgDroneBay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgDroneControl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgDroneControl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgEMResist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgEMResist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgExplosiveResist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgExplosiveResist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgGanglink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgGanglink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgHiSlot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgHiSlot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgInertia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgInertia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgInfo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgInfo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgInfo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgInfo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgKineticResist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgKineticResist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgLauncherSlots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLauncherSlots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgLog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgLogistics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLogistics", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgLowSlot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLowSlot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgMaxTargets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgMaxTargets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgMidSlot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgMidSlot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgMining() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgMining", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPrice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPrice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgRigSlot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRigSlot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgScannable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgScannable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgScanResolution() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgScanResolution", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSensorStregthL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSensorStregthL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSensorStrengthG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSensorStrengthG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSensorStrengthM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSensorStrengthM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSensorStrengthR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSensorStrengthR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgShield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgShield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSigRadius() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSigRadius", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSmartbomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSmartbomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSpeed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSpeed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgStructure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgStructure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSubSlot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSubSlot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTargetRange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTargetRange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgThermalResist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgThermalResist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTimer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTimer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTurretSlots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTurretSlots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgWarpAlign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgWarpAlign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgWarpSpeed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgWarpSpeed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #HQF Implant Mapping Table,,,,,,,,,,
        '''#Affecting Attribute,Affecting Type,Affecting ID,Affected Attribute,Affected Type,Affected ID,Calc Type,State,IsGang,Group,Implant Name
        '''# Pirate Sets
        '''624,1,33516,1281,3,6,0,0,0,Navigation;Learning,High-grade Ascendancy Alpha
        '''624,1,33525,1281,3,6,0,0,0,Navigation;Learning,High-grade Ascendancy Beta
        '''624,1,33526,1281,3,6,0,0,0,Navigation;Learning,High-grade Ascendancy Delta
        '''624,1,33527,1281,3,6,0,0,0,Navigation;Learning,High-grade Ascendancy Epsilon
        '''624,1,33528,1281, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ImplantEffects() As String
            Get
                Return ResourceManager.GetString("ImplantEffects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Level0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Level1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Level2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Level3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Level4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Level5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meta1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meta1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meta16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meta16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meta2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meta2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meta32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meta32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meta4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meta4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meta4096() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meta4096", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meta8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meta8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meta8192() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meta8192", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mod01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mod01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mod02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mod02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mod02a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mod02a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mod04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mod04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mod08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mod08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 100MN MicroWarpdrive I,100MN Microwarpdrive I
        '''100MN MicroWarpdrive II,100MN Microwarpdrive II
        '''10MN MicroWarpdrive I,10MN Microwarpdrive I
        '''10MN MicroWarpdrive II,10MN Microwarpdrive II
        '''1200mm Heavy Gallium I Cannon,1200mm Heavy Gallium Cannon
        '''1200mm Heavy Prototype I Artillery,1200mm Heavy Prototype Artillery
        '''1200mm Heavy Prototype I Siege Cannon,1200mm Heavy Prototype Siege Cannon
        '''125mm Light Gallium I Machine Gun,125mm Light Gallium Machine Gun
        '''125mm Light Prototype I Automatic Cannon,125mm Light P [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ModuleChanges() As String
            Get
                Return ResourceManager.GetString("ModuleChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4579,1050,1
        '''4621,1051,1
        '''10210,0,0
        '''10211,0,0
        '''10214,0,0
        '''10215,0,0
        '''10218,0,0
        '''10219,0,0
        '''10223,0,0
        '''10224,0,0
        '''10227,0,0
        '''20371,627,0
        '''20443,624,0
        '''20700,624,0
        '''21606,627,0
        '''22715,620,0
        '''22760,618,0
        '''24663,625,0
        '''24669,624,0
        '''25867,627,0
        '''25868,626,0
        '''25922,0,0
        '''26336,0,0
        '''27080,627,0
        '''27091,623,0
        '''27204,623,0
        '''27205,623,0
        '''27206,623,0
        '''27213,623,0
        '''27214,623,0
        '''27215,623,0
        '''27216,623,0
        '''27217,623,0
        '''27218,623,0
        '''27219,624,0
        '''27220,624,0
        '''27221,624,0
        '''28262,837,0
        '''28264,837,0
        '''28266,839,0
        '''28268,839,0
        '''2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property newItemMarketGroup() As String
            Get
                Return ResourceManager.GetString("newItemMarketGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noitem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noitem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nomode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nomode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plugin_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plugin_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #HQF Ship Bonus Mapping Table,,,,,,,,,,,
        '''#Ship ID,Affecting Type,Affecting ID,Affected Attribute,Affected Type,Affected ID,Stack Nerf,Per Level,Calc Type,Value,Status,Description
        '''# Abaddon,,,,,,,,,,,
        '''24692,1,3339,10014,4,569;573,0,1,0,5,15,Large Energy Turret Damage
        '''24692,1,3339,267,1,24692,0,1,2,-4,15,Armor EM Resistance
        '''24692,1,3339,268,1,24692,0,1,2,-4,15,Armor Explosive Resistance
        '''24692,1,3339,269,1,24692,0,1,2,-4,15,Armor Kinetic Resistance
        '''24692,1,3339,270,1,24692,0,1,2,-4,15,Armor Thermal Resi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShipBonuses() As String
            Get
                Return ResourceManager.GetString("ShipBonuses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #HQF Ship Attribute Mapping Table,,,,,,,,,,
        '''#Affecting Attribute,Affecting Type,Affecting ID,Affected Attribute,Affected Type,Affected ID,Stack Nerf,Per Level,Calc Type,State,Description
        '''# SHIPS,,,,,,,,,,
        '''1034,3,6,669,2,330,0,0,4,15,Cloak Reactivation Delay.
        '''</summary>
        Friend ReadOnly Property ShipEffects() As String
            Get
                Return ResourceManager.GetString("ShipEffects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #HQF Ship Mode Bonus Mapping Table,,,,,,,,,,,
        '''#Ship ID,Ship Mode,Affecting Type,Affecting ID,Affected Attribute,Affected Type,Affected ID,Stack Nerf,Per Level,Calc Type,Value,Status,Description
        '''# Confessor,,,,,,,,,,,,
        '''34317,1,0,0,267,1,34317,0,1,2,-33.33333333,15,Defence Mode - Armor EM Resistence
        '''34317,1,0,0,268,1,34317,0,1,2,-33.33333333,15,Defence Mode - Armor Explosive Resistence
        '''34317,1,0,0,269,1,34317,0,1,2,-33.33333333,15,Defence Mode - Armor Kinetic Resistence
        '''34317,1,0,0,270,1,34317,0,1,2,-33 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShipModeBonuses() As String
            Get
                Return ResourceManager.GetString("ShipModeBonuses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SkillBook32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillBook32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SkillBook64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillBook64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SkillBookClosed32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillBookClosed32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SkillBookClosed64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillBookClosed64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skills0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skills0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skills1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skills1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skills2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skills2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property speed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #HQF Subsystem Bonus Mapping Table,,,,,,,,,,,
        '''#Type ID,Affecting Type,Affecting ID,Affected Attribute,Affected Type,Affected ID,Stack Nerf,Per Level,Calc Type,Value,Status,Description
        '''# Defensive Subsystems,,,,,,,,,,,
        '''# Legion Defensive - Adaptive Augmenter,,,,,,,,,,,
        '''29964,1,30532,267,1,29986,0,1,2,-4,15,Armor EM Resistance
        '''29964,1,30532,268,1,29986,0,1,2,-4,15,Armor Explosive Resistance
        '''29964,1,30532,269,1,29986,0,1,2,-4,15,Armor Kinetic Resistance
        '''29964,1,30532,270,1,29986,0,1,2,-4,15,Armor Therma [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Subsystems() As String
            Get
                Return ResourceManager.GetString("Subsystems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property target() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("target", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MassIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MassIcon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
