'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Resources
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("EveHQ"),  _
 Assembly: AssemblyDescription("Eve Online game tool"),  _
 Assembly: AssemblyCompany("EveHQ Development Team"),  _
 Assembly: AssemblyProduct("EveHQ"),  _
 Assembly: AssemblyCopyright("� EveHQ Development Team 2005-2014"),  _
 Assembly: AssemblyFileVersion("2.15.0.$REVNUM$"),  _
 Assembly: AssemblyVersion("2.15.0.$REVNUM$"),  _
 Assembly: AssemblyConfiguration("Release"),  _
 Assembly: AssemblyTrademark("$UTCDATE$ (Version 2.15.0.$REVNUM$)"),  _
 Assembly: CLSCompliant(false),  _
 Assembly: ComVisible(false),  _
 Assembly: Guid("f8be6b56-f761-4ee7-a722-da54af312ecb")> 

