'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EveHQ.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AchuraBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AchuraBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AmarrBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AmarrBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AmarrRace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AmarrRace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AssetsSafe32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AssetsSafe32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Attributes32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attributes32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aura32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aura32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BrutorBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BrutorBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CaldariRace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CaldariRace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cert0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cert0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cert1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cert1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cert2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cert2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cert3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cert3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cert4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cert4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cert5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cert5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Charisma32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Charisma32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chart32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chart32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CivireBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CivireBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dashboard32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dashboard32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Database32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeteisBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeteisBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Document32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Document32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        '''&lt;eveapi version=&quot;2&quot;&gt;
        '''  &lt;currentTime&gt;2011-08-13 18:37:28&lt;/currentTime&gt;
        '''  &lt;result&gt;
        '''    &lt;rowset name=&quot;errors&quot; key=&quot;errorCode&quot; columns=&quot;errorCode,errorText&quot;&gt;
        '''      &lt;row errorCode=&quot;100&quot; errorText=&quot;Expected before ref/trans ID = 0: wallet not previously loaded.&quot; /&gt;
        '''      &lt;row errorCode=&quot;101&quot; errorText=&quot;Wallet exhausted: retry after {0}.&quot; /&gt;
        '''      &lt;row errorCode=&quot;102&quot; errorText=&quot;Expected before ref/trans ID [{0}] but supplied [{1}]: wallet previously loaded.&quot; /&gt;
        '''      [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Errors() As String
            Get
                Return ResourceManager.GetString("Errors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property EveHQ() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("EveHQ", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property EveHQ_offline() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("EveHQ_offline", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property EveHQ_online() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("EveHQ_online", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property EveHQ_starting() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("EveHQ_starting", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EveHQErrorProf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EveHQErrorProf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EveHQSplash9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EveHQSplash9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EveMail32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EveMail32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exit32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Folder32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GallenteBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GallenteBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GallenteRace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GallenteRace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Help32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IGB32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IGB32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImplantFormSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImplantFormSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Implants32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Implants32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Info32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IntakiBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IntakiBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Intelligence32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Intelligence32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jin_MeiBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jin_MeiBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KhanidBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KhanidBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ki_NunniBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ki_NunniBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_020() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_020", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_040() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_040", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_120() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_120", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_130() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_130", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_140() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_140", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_150() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_150", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_230() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_230", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_250() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_250", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_340() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_340", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_350() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_350", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_450() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_450", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level1_act() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level1_act", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level2_act() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level2_act", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level3_act() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level3_act", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level4_act() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level4_act", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level5_act() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level5_act", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoadRSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadRSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoadRSS2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadRSS2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ManageAPI32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ManageAPI32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Market32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Market32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Memory32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Memory32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinmatarRace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinmatarRace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NeuralRemapFormSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NeuralRemapFormSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nochar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nochar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noitem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noitem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Orders32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Orders32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perception32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perception32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QueryAPI32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueryAPI32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1,3300,2
        '''1,3301,3
        '''1,3327,3
        '''1,3330,2
        '''1,3386,2
        '''1,3392,2
        '''1,3402,3
        '''1,3413,3
        '''1,3416,2
        '''1,3426,3
        '''1,3449,3
        '''2,3300,2
        '''2,3302,3
        '''2,3327,3
        '''2,3329,2
        '''2,3386,2
        '''2,3392,2
        '''2,3402,3
        '''2,3413,3
        '''2,3416,2
        '''2,3426,3
        '''2,3449,3
        '''4,3300,2
        '''4,3303,3
        '''4,3327,3
        '''4,3331,2
        '''4,3386,2
        '''4,3392,2
        '''4,3402,3
        '''4,3413,3
        '''4,3416,2
        '''4,3426,3
        '''4,3449,3
        '''8,3300,2
        '''8,3301,3
        '''8,3327,3
        '''8,3328,2
        '''8,3386,2
        '''8,3392,2
        '''8,3402,3
        '''8,3413,3
        '''8,3416,2
        '''8,3426,3
        '''8,3449,3
        '''.
        '''</summary>
        Friend ReadOnly Property RaceSkillsTable() As String
            Get
                Return ResourceManager.GetString("RaceSkillsTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SebiestorBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SebiestorBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SecureCan32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecureCan32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Settings32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SkillBook16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillBook16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SkillBook32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillBook32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VherokiorBlood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VherokiorBlood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Warning64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 30463,1381,9
        '''30463,1382,3600
        '''30463,1383,1000000000
        '''30463,1384,50000000
        '''30463,1385,150000000
        '''30463,1457,0
        '''30579,1381,1
        '''30579,1382,960
        '''30579,1383,100000000
        '''30579,1384,0
        '''30579,1385,20000000
        '''30579,1457,296
        '''30583,1381,2
        '''30583,1382,960
        '''30583,1383,750000000
        '''30583,1384,0
        '''30583,1385,300000000
        '''30583,1457,297
        '''30584,1381,3
        '''30584,1382,1440
        '''30584,1383,1000000000
        '''30584,1384,0
        '''30584,1385,300000000
        '''30584,1457,298
        '''30642,1381,4
        '''30642,1382,1440
        '''30642,1383,1000000000
        '''30642,1384,0
        '''30642,1385,300000000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WHattribs() As String
            Get
                Return ResourceManager.GetString("WHattribs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 11000001,1
        '''11000002,1
        '''11000003,1
        '''11000004,2
        '''11000005,2
        '''11000006,2
        '''11000007,2
        '''11000008,2
        '''11000009,3
        '''11000010,3
        '''11000011,3
        '''11000012,3
        '''11000013,3
        '''11000014,3
        '''11000015,3
        '''11000016,4
        '''11000017,4
        '''11000018,4
        '''11000019,4
        '''11000020,4
        '''11000021,4
        '''11000022,4
        '''11000023,4
        '''11000024,5
        '''11000025,5
        '''11000026,5
        '''11000027,5
        '''11000028,5
        '''11000029,5
        '''11000030,6
        '''.
        '''</summary>
        Friend ReadOnly Property WHClasses() As String
            Get
                Return ResourceManager.GetString("WHClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 146,2,920,263,3,6,0,0,0,15,Shield HP Bonus
        '''169,2,920,70,3,6,0,0,5,15,Inertia Modifer
        '''237,2,920,76,3,6,0,0,0,15,Targeting Range Bonus
        '''243,2,920,76,3,6,0,0,5,15,Max Range Multiplier
        '''244,2,920,160,2,53;55;74,0,0,5,15,Tracking Speed Multiplier
        '''517,2,920,158,2,53;55;74,0,0,5,15,Falloff Modifer
        '''652,2,920,552,3,6,0,0,0,15,Signature Penalty
        '''1465,2,920,267,3,6,0,0,2,15,Armor EM Resistance Bonus
        '''1466,2,920,269,3,6,0,0,2,15,Armor Kin Resistance Bonus
        '''1467,2,920,270,3,6,0,0,2,15,Armor Therm Resistance Bonus
        '''1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WHEffects() As String
            Get
                Return ResourceManager.GetString("WHEffects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Willpower32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Willpower32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to J100009,Pulsar
        '''J100040,Black Hole
        '''J100046,Cataclysmic Variable
        '''J100118,Magnetar
        '''J100150,Black Hole
        '''J100237,Wolf Rayet
        '''J100328,Black Hole
        '''J100422,Red Giant
        '''J100447,Black Hole
        '''J100616,Pulsar
        '''J100651,Red Giant
        '''J100702,Black Hole
        '''J100724,Red Giant
        '''J100728,Red Giant
        '''J100744,Cataclysmic Variable
        '''J100846,Black Hole
        '''J100919,Wolf Rayet
        '''J100937,Cataclysmic Variable
        '''J101000,Cataclysmic Variable
        '''J101012,Red Giant
        '''J101042,Cataclysmic Variable
        '''J101145,Pulsar
        '''J101336,Cataclysmic Variable
        '''J101343,Wol [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WSpaceTypes() As String
            Get
                Return ResourceManager.GetString("WSpaceTypes", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
