//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Software Addicts Studios")]
[assembly: AssemblyProduct("EveHQ")]
[assembly: AssemblyCopyright("� EveHQ Development Team 2005-2013")]
[assembly: AssemblyFileVersion("2.12.0")]
[assembly: AssemblyVersion("2.12.0")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyTrademark("$UTCDATE$ (Version 2.12.0)")]
[assembly: CLSCompliant(false)]
[assembly: ComVisible(false)]


