//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("EveHQ Development Team")]
[assembly: AssemblyProduct("EveHQ")]
[assembly: AssemblyCopyright("� EveHQ Development Team 2005-2014")]
[assembly: AssemblyFileVersion("2.15.0.$REVNUM$")]
[assembly: AssemblyVersion("2.15.0.$REVNUM$")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyTrademark("$UTCDATE$ (Version 2.15.0.$REVNUM$)")]
[assembly: CLSCompliant(false)]
[assembly: ComVisible(false)]


