//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("EveHQ.CoreControls")]
[assembly: AssemblyDescription("Eve Online game tool")]
[assembly: AssemblyCompany("Software Addicts Studios")]
[assembly: AssemblyProduct("EveHQ")]
[assembly: AssemblyCopyright("� EveHQ Development Team 2005-2013")]
[assembly: AssemblyFileVersion("2.12.3.$REVNUM$-Beta20131002212912")]
[assembly: AssemblyVersion("2.12.3.$REVNUM$")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyTrademark("$UTCDATE$ (Version 2.12.3.$REVNUM$-Beta20131002212912)")]
[assembly: CLSCompliant(false)]
[assembly: ComVisible(false)]
[assembly: Guid("c2bf7a31-3953-47e3-823f-8971cd42b938")]


